[build]
  command = "npm run build"
  publish = "build"
  base = "GPT5 (code source)"
  
[context.production.environment]
  NODE_ENV = "production"
  
[context.split1]
  command = "npm run build:split1"
  publish = "split1"
  
[context.split1.environment]
  NODE_ENV = "production"
